<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * JWT Configuration for the MDCAT Platform REST API.
 *
 * Centralizes all JWT settings: signing algorithm, token lifetimes,
 * issuer identity, and secret key resolution.
 *
 * Token lifetimes are filterable so site administrators or companion
 * plugins can adjust them without editing this file:
 *
 *     // Example: shorten access tokens to 1 hour.
 *     add_filter('mdcat_jwt_access_token_expiry', function () {
 *         return 3600;
 *     });
 *
 *     // Example: extend refresh tokens to 90 days.
 *     add_filter('mdcat_jwt_refresh_token_expiry', function () {
 *         return 90 * DAY_IN_SECONDS;
 *     });
 *
 * The signing secret is resolved via a fallback chain rather than
 * assuming AUTH_KEY is always defined, because:
 *
 *   - Some hosting environments strip AUTH_KEY from wp-config.php.
 *   - Managed WordPress hosts may define salts via environment
 *     variables, making AUTH_KEY unavailable as a PHP constant.
 *   - wp_salt('auth') is WordPress's own API for retrieving the
 *     auth salt and handles edge cases internally.
 *
 * Resolution order:
 *   1. AUTH_KEY constant (if defined and non-empty)
 *   2. wp_salt('auth') (WordPress core fallback)
 *   3. WP_Error (no usable secret — JWT cannot function)
 */
class MDCAT_Platform_JWT_Config {

    /**
     * Signing algorithm.
     *
     * HS256 (HMAC-SHA256) is a symmetric algorithm — the same key
     * is used for signing and verification. Appropriate when the
     * signer and verifier are the same server (our case).
     */
    const ALGORITHM = 'HS256';

    /**
     * Token type claim: access token.
     *
     * Stored in the JWT payload as the 'type' claim to distinguish
     * access tokens from refresh tokens during validation.
     */
    const TOKEN_TYPE_ACCESS = 'access';

    /**
     * Token type claim: refresh token.
     *
     * Stored in the JWT payload as the 'type' claim. The refresh
     * endpoint only accepts tokens with this type, preventing
     * access tokens from being used to obtain new tokens.
     */
    const TOKEN_TYPE_REFRESH = 'refresh';

    /**
     * Default access token lifetime in seconds (24 hours).
     *
     * This is the fallback value before the filter is applied.
     * Long enough for a full study session, short enough to limit
     * the window of a stolen token.
     */
    const DEFAULT_ACCESS_TOKEN_EXPIRY = 86400;

    /**
     * Default refresh token lifetime in seconds (30 days).
     *
     * This is the fallback value before the filter is applied.
     * Students should not need to re-enter credentials for a
     * month under normal usage.
     */
    const DEFAULT_REFRESH_TOKEN_EXPIRY = 2592000;

    /**
     * Get the access token expiry duration in seconds.
     *
     * Filterable via 'mdcat_jwt_access_token_expiry'. The returned
     * value is clamped to a minimum of 300 seconds (5 minutes) to
     * prevent misconfiguration from making the API unusable.
     *
     * @return int Expiry duration in seconds.
     */
    public static function get_access_token_expiry() {

        /**
         * Filter the access token lifetime.
         *
         * @param int $expiry Duration in seconds. Default 86400 (24 hours).
         */
        $expiry = apply_filters('mdcat_jwt_access_token_expiry', self::DEFAULT_ACCESS_TOKEN_EXPIRY);

        return max(300, absint($expiry));
    }

    /**
     * Get the refresh token expiry duration in seconds.
     *
     * Filterable via 'mdcat_jwt_refresh_token_expiry'. The returned
     * value is clamped to a minimum of 3600 seconds (1 hour) to
     * prevent misconfiguration from making refresh tokens useless.
     *
     * @return int Expiry duration in seconds.
     */
    public static function get_refresh_token_expiry() {

        /**
         * Filter the refresh token lifetime.
         *
         * @param int $expiry Duration in seconds. Default 2592000 (30 days).
         */
        $expiry = apply_filters('mdcat_jwt_refresh_token_expiry', self::DEFAULT_REFRESH_TOKEN_EXPIRY);

        return max(3600, absint($expiry));
    }

    /**
     * Get the token issuer (WordPress site URL).
     *
     * Used as the 'iss' claim in JWT payloads. During validation,
     * the issuer claim is compared against this value to reject
     * tokens generated by a different WordPress installation.
     *
     * @return string Site URL.
     */
    public static function get_issuer() {

        return get_bloginfo('url');
    }

    /**
     * Get the JWT signing secret key.
     *
     * Resolution order:
     *   1. AUTH_KEY constant — defined in wp-config.php on standard
     *      WordPress installations. Preferred because it is unique
     *      per site and already used for cookie authentication.
     *   2. wp_salt('auth') — WordPress core API that retrieves the
     *      auth salt from wp-config.php or generates a fallback.
     *      Covers managed hosting environments where AUTH_KEY may
     *      not be a PHP constant.
     *   3. WP_Error — returned if neither source yields a usable
     *      secret. The JWT Handler must check for this and refuse
     *      to sign or verify tokens.
     *
     * @return string|WP_Error The secret key, or WP_Error if unavailable.
     */
    public static function get_secret_key() {

        // 1. Prefer AUTH_KEY if defined and non-empty.
        if (defined('AUTH_KEY') && AUTH_KEY !== '' && AUTH_KEY !== 'put your unique phrase here') {
            return AUTH_KEY;
        }

        // 2. Fallback to WordPress salt API.
        $salt = wp_salt('auth');

        if (!empty($salt)) {
            return $salt;
        }

        // 3. No usable secret available.
        return new WP_Error(
            'jwt_secret_missing',
            __('JWT signing secret is not configured. Define AUTH_KEY in wp-config.php.', 'mdcat-platform')
        );
    }
}
